# Generated by Django 2.2 on 2021-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default='Enter a short description.', max_length=100),
        ),
    ]
